name: Notify Guilded
on: [push, pull_request]

jobs:
  webhook:
    name: Notify Guilded
    runs-on: ubuntu-latest
    steps:
      - uses: guildedjs/guilded-webhook-action@v1
        env:
          WEBHOOK_URL: "https://media.guilded.gg/webhooks/438e6641-dde4-4ce5-ba0b-65834e892ba2/uHMTCLh1W8Eiu8gYg2YieuSwGoU8aQcWuG46AaSqEyQeOes44qKeiyUaII8wSAQq4iAKqaQos0aYIqCYgmQKKi"
          WEBHOOK_USERNAME: "Github"
          WEBHOOK_AVATAR: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
        with:
          title: ${{ github.event.head_commit.message }}
          description: ${{ github.event.head_commit.url }}
      
